### ISSUE TITLE
Ollama support

### ISSUE THREAD

**Issue by dxcore35** [TfTHacker/obsidian-ai-templater#2]
Please support local models on Ollama. As I know the API is almost same!
Thank you. I have been looking for Templater and AI connection for so long.

**Comment by TfTHacker** [comment]
I have tested this with LM studio. Have you tried with Ollam's? I haven't.

**Comment by TfTHacker** [comment]
I had a chance to look closer, and well, ollama has a CORS issue with the openai library. I think this will get fixed..

LM Studio requires CORS to be on and it works just fine.

**Comment by dxcore35** [comment]
Any updates on this?

**Comment by TfTHacker** [comment]
@dxcore35 I just tested this with the most recent update to Ollama and it worked for me. The issue was related to how they handle CORS, so it was a limitation in their API. Please let me know if it works for you now.
