### ISSUE TITLE
Does this work on mobile?

### ISSUE THREAD

**Issue by Cossackx** [TfTHacker/obsidian-ai-templater#5]
Thanks for this plugin TfTHacker. I have this triggering on my daily note along with a few other templater operations. Does your plugin work on mobile? If so, I have not figured out what I'm not doing right.

**Comment by TfTHacker** [comment]
Hi. Thank you for your kind words. Yes, I use this on my mobile daily. Perhaps create a very simple template for Templater that performs an AI command to see if it works? Perhaps it has something to do with: (1) are your settings syncing? (2) is Templater triggering properly? I am not saying any of these things are a problem but might help with troubleshooting.
