### ISSUE TITLE
Please add support for Local AIs

### ISSUE THREAD

**Issue by dxcore35** [TfTHacker/obsidian-ai-templater#6]
Lot of local AI is using OpenAI standard connection (Ollama has their own implementation). It will be amazing to add support to add custom url for local AI.

You can steal code from https://github.com/logancyang/obsidian-copilot. There is already implementation for:

- OpenAI
- Azure
- Google
- Anthropic
- OpenRouter
- Groq
- Cohere
- Third-party models with OpenAI-compatible APIs via Custom Model

**Comment by TfTHacker** [comment]
The OpenAI API is supported with any endpoint. Now working with Ollama https://github.com/TfTHacker/obsidian-ai-templater/issues/2#issuecomment-2260331311

Just set the endpoint in settings or JavaScript in the template.
